### ISSUE TITLE
Add curl to image for use native HEALTHCHECK 

### ISSUE THREAD

**Issue by 4n70w4** [containous/whoami#33]

**Comment by JaneJeon** [comment]
Would love this as well. Some form of built-in healthcheck would be nice.

**Comment by viharm** [comment]
Yes, it would be good to have any form of healthcheck.

**Comment by pduchnovsky** [comment]
in the meantime you guys could do this (dockerfile_inline works in newer docker-compose versions):
```
version: '2.4'
services:
  whoami:
    container_name: whoami
    build:
      context: .
      dockerfile_inline: |
        FROM traefik/whoami
        COPY --from=ghcr.io/tarampampam/curl:8.4.0 /bin/curl /curl
        HEALTHCHECK --interval=5s --timeout=2s --retries=2 --start-period=2s CMD ["/curl", "--fail", "http://127.0.0.1:80/health"]
    restart: always
    mem_limit: 16m
    memswap_limit: 16m
```
